# Generated by Django 5.1.6 on 2025-02-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_rename_room_name_room_room_numbers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country_name',
            field=models.CharField(max_length=32),
        ),
    ]
