# Generated by Django 5.1.6 on 2025-02-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_booking_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RemoveField(
            model_name='city',
            name='country_en',
        ),
        migrations.RemoveField(
            model_name='city',
            name='country_ru',
        ),
        migrations.AddField(
            model_name='city',
            name='city_image',
            field=models.ImageField(default=1, upload_to='city_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='country',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
