# Generated by Django 5.1.6 on 2025-02-11 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_remove_city_country_remove_city_country_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='hotel',
            new_name='booking',
        ),
        migrations.AlterField(
            model_name='review',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='hotel.hotel'),
        ),
    ]
