# Generated by Django 5.1.6 on 2025-02-11 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_rename_hotel_booking_booking_alter_review_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='hotel.hotel'),
        ),
    ]
