# Generated by Django 5.1.6 on 2025-02-12 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_roomimage_review_comfort_review_free_wifi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='comfort',
        ),
        migrations.RemoveField(
            model_name='review',
            name='free_WiFi',
        ),
        migrations.RemoveField(
            model_name='review',
            name='location',
        ),
        migrations.RemoveField(
            model_name='review',
            name='person',
        ),
        migrations.RemoveField(
            model_name='review',
            name='purity',
        ),
    ]
