# Generated by Django 5.1.6 on 2025-02-12 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_remove_review_comfort_remove_review_free_wifi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomimage',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotel.room'),
            preserve_default=False,
        ),
    ]
