# Generated by Django 5.1.6 on 2025-02-12 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_room_hotel_alter_roomimage_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelimages',
            old_name='image',
            new_name='hotel_image',
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_image', to='hotel.room'),
        ),
    ]
