# Generated by Django 5.1.6 on 2025-02-12 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_roomimage_hotel_alter_hotelimages_hotel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking',
            new_name='booking_hotel',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_city', to='hotel.city'),
        ),
    ]
